apiVersion: v1
kind: Namespace
metadata:
  name: {{.NameSpace}}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{.SecretName}}
  namespace: {{.NameSpace}}
type: Opaque
data:
{{- range $key, $value := .SecretData}}
  {{$key}}: {{$value -}}
{{end}}